### ISSUE TITLE
Site navigation blocks translation navigation

### ISSUE THREAD

**Issue by mrdokenny** [andreicristianpetcu/google_translate_this#1]
STR:
1. Go to:
https://www.nytimes.com/2017/05/12/world/europe/uk-national-health-service-cyberattack.html?_r=0

2. Click extension button

Actual:
Site navigation blocks the translation navigation.

Expected:
Translation nav should overlay on top of the website's nav. Maybe something you could do with Web APIs to make the translation nav overlay on top?

**Comment by andreicristianpetcu** [comment]
Thank you @mrdokenny for the bug report. I looked into this issue. I will try to fix this problem sometime but I have not prediction on the time it will be fixed :( 

Pull requests are welcome :D

**Comment by andreicristianpetcu** [comment]
Does this still happen for you? I'm running the latest version and it seems to work. Maybe I don't understand the issue and I forgot how to reproduce it :smile: https://github.com/andreicristianpetcu/google_translate_this/releases/tag/v2.0.0
