### ISSUE TITLE
No longer translates ftp sites?

### ISSUE THREAD

**Issue by TheEliteGeek** [andreicristianpetcu/google_translate_this#10]
For some reason, this utility no longer translates ftp pages opened in Firefox.
FF Quantum 68.0.2 (64-bit)

The option to "Always translate xxxx" appears but clicking it does not do anything.

**Comment by andreicristianpetcu** [comment]
Do you have a public page I can test on?

**Comment by andreicristianpetcu** [comment]
try this extension, maybe it will work until I fix this issue https://github.com/jeremiahlee/page-translator

**Comment by TheEliteGeek** [comment]
Sorry, I should have included an example ftp site for you to test this with.
Here is a public site which uses "ftp" as the schema.
ftp://ftp.cs.brown.edu/pub/

It's not the *best* test site since there aren't really that many words to translate on it, but it might be enough to help you debug the add-on. I appreciate it!

**Comment by andreicristianpetcu** [comment]
I fixed the support for FTP sites. Just update it and tell me if it's ok. @TheEliteGeek

**Comment by TheEliteGeek** [comment]
> 
> 
> I fixed the support for FTP sites. Just update it and tell me if it's ok. @TheEliteGeek

It works! Huzzuh! You are a rockstar!

Just one more thing...The translate option no longer shows up in the right-click context menu or address bar :D 

Fix one bug and more will spawn! Hehe!

PS: How do I donate to you?

**Comment by andreicristianpetcu** [comment]
@TheEliteGeek I made another update. I fixed the issue you mentioned.
I do this for fun. But if you want to help out and speak another language besides English, please translate the extension in another language. You just need to add another file like this one https://github.com/andreicristianpetcu/google_translate_this/blob/master/_locales/en/messages.json or like this https://github.com/andreicristianpetcu/google_translate_this/blob/master/_locales/ro/messages.json
