### ISSUE TITLE
Plugin don't work?

### ISSUE THREAD

**Issue by BakasuraRCE** [andreicristianpetcu/google_translate_this#12]
Hi,

I'm using the version 2.3.1 and now the plugin only show the options "Always translate X" and "Never translate X" but don't show any toolbar or some.

Can help me?

**Comment by andreicristianpetcu** [comment]
Hi! What exactly are you trying to do and what is the actual result?

**Comment by andreicristianpetcu** [comment]
maybe it's related to this https://github.com/andreicristianpetcu/google_translate_this/issues/9

Also.... what sitw are you having issues with?

**Comment by BakasuraRCE** [comment]
I don't know if I'm doing it wrong, I have the plugin installed, but only the option "Always translate X" and "Never translate X" appears in the context menu, the plugin icon appears in the address bar and if I give it click just change the option "Always translate X" and "Never translate X", but in case I never see the translation bar, in any case, I don't know what I'm doing wrong.

**Comment by andreicristianpetcu** [comment]
What version of Firefox are you using? what web page are you having issues with? Are you willing to do a bit of debugging? @BakasuraRCE

**Comment by BakasuraRCE** [comment]
Im using the version Firefox version 68.0.2 (64-bit) and have problems with all web pages, sure, just let me known what I do

**Comment by BakasuraRCE** [comment]
Ok, I find the problem, was about my config of "privacy.firstparty.isolate = True" on my firefox:

https://www.bleepingcomputer.com/news/software/another-tor-browser-feature-makes-it-into-firefox-first-party-isolation/

I will close it,

Ty.
