### ISSUE TITLE
Why consume a lot of performance?

### ISSUE THREAD

**Issue by LArctic** [andreicristianpetcu/google_translate_this#18]
Looking at Firefox's performance through "about:performance", I found that "Google Translate This Page" takes up a lot of performance (when loading a new page, and this page doesn't trigger it), second only to "Tampermonkey".
This surprised me a lot. I always thought that "Google Translate This Page" is roughly equivalent to a "button" and does not affect the performance of the browser.

Is this reasonable?

**Comment by andreicristianpetcu** [comment]
Strange. That is what I thought also, and I wrote it :D Any chance you can record a perf profile and share the link with me? 

https://vimeo.com/269371096

https://vimeo.com/269371201

**Comment by andreicristianpetcu** [comment]
It might be the fact that it changes the CSP for the current page if it uses CSP but that should be reallt limmited.

**Comment by andreicristianpetcu** [comment]
Here is my perf profile on my main profile https://perfht.ml/2Jw358C for me it really does not use a lot

**Comment by andreicristianpetcu** [comment]
Disabling CSP does not help.
CSP is a way in which a server tells a browser "please run file1.js, file2.js and file3.css". The browser banns everything else, including stuff from [translate.google.com](https://github.com/andreicristianpetcu/google_translate_this/blob/master/scripts/inject_google_translate_content.js#L22) :disappointed: 

This is good for security but bad for me. On every page load I say: "wait browser, please allow file1.js, file2.js, file3.css aaaaaand [translate.google.com](https://github.com/andreicristianpetcu/google_translate_this/blob/master/scripts/inject_google_translate_content.js#L22)"

This seems to take a bit of time :disappointed: As you can see the code that does this is non-trivial https://github.com/andreicristianpetcu/google_translate_this/blob/194e404cd6d8683140f945afa656db669cc3e0a7/scripts/background.js#L101-L149 

I will investigate more when I get a bit of time.

**Comment by andreicristianpetcu** [comment]
Hmmm.... my assumption was wrong. It seems like [updateMenuForDomain](https://github.com/andreicristianpetcu/google_translate_this/blob/194e404cd6d8683140f945afa656db669cc3e0a7/scripts/background.js#L202) is causing all the fuss.

It seems to have a very small portion of the performance issue.
![image](https://user-images.githubusercontent.com/922368/67784287-85ee1a80-faa6-11e9-8629-86911aae9598.png)

Check out my filter on your data. I'm looking at what the WebExtension process is doing. My extension is not doing anything in other processes. Google translate is doing some heavy work on demand in the content process but that should not be an issue since it's on demand.

Go ahead, play with the data.... maybe drill down into a specific section or period of time that I missed. https://perfht.ml/349ucyb

**Comment by LArctic** [comment]
I created a new configuration and only loaded one extension.

https://youtu.be/GGonFCIfAOw

**Comment by andreicristianpetcu** [comment]
Brand new profile. Your use case with different web sites. Here is the data. https://perfht.ml/36cjCIF
Will try to investigate the usage of these methods. Will report back.

**Comment by LArctic** [comment]
I have a doubt, can it be used in the form of a Tampermonkey script?

**Comment by andreicristianpetcu** [comment]
Hmmmm. I will look into this. It will not work for sure on pages with CSP 😞 

I made a fix for the perf issue but I cannot ship new updates to the extension.

**Comment by LArctic** [comment]
Thank you. Where can I find new xpi files?

**Comment by andreicristianpetcu** [comment]
I cannot ship new versions :( you have to build it yourself https://github.com/andreicristianpetcu/google_translate_this/issues/19#issuecomment-549142899

I will publish an unsigned xpi file once I get to my laptop but not a signed one.

**Comment by andreicristianpetcu** [comment]
Try this. It's not signed so you need to disable xpi signing.
[tr_desktop.zip](https://github.com/andreicristianpetcu/google_translate_this/files/3802734/tr_desktop.zip)

**Comment by LArctic** [comment]
Thanks. But even if I disable extension verification, it still can't be installed.

**Comment by andreicristianpetcu** [comment]
Hmm. It works for me. I made a new profile in Firefox Nightly from about:profiles. I flipped the `xpinstall.signatures.required` to false in `about:config` then renamed `tr_desktop.zip` to `tr_desktop.xpi` (github does not allow xpi attachments here for some reason) and dragged the xpi on the Firefox window. Hit Ok and it worked. @LArctic

**Comment by LArctic** [comment]
Yes, but this is only valid in the "nightly" version.

**Comment by yoasif** [comment]
It should also work in developer edition: https://www.mozilla.org/firefox/developer/

**Comment by andreicristianpetcu** [comment]
It should work in DevEdition also which is awesome
