### ISSUE TITLE
Add target translation language

### ISSUE THREAD

**Issue by BakasuraRCE** [andreicristianpetcu/google_translate_this#2]
It would be great to be able to define the default translation language

**Comment by andreicristianpetcu** [comment]
I tried to do this in the past. It's really complicated. I would accept a PR from somebody more clever than I am :smile:

**Comment by andreicristianpetcu** [comment]
This was fixed in this build https://github.com/andreicristianpetcu/google_translate_this/releases/tag/v2.1.0
I will push it as an update soon. If you can test it before that @BakasuraRCE it would be awesome!
