### ISSUE TITLE
Cannot Install Because of High Risk of Causing Stability or Security Problems

### ISSUE THREAD

**Issue by ghost** [andreicristianpetcu/google_translate_this#25]
**OS:** Windows 10 Home
**Firefox:** 76.0.1 (64-bit)

**Issue:** When trying to install the Desktop version of this app, I get a message from Mozilla Firefox indicating the following: _"Google Translate This Page could not be installed because it has a high risk of causing stability or security problems."_

![GoogleTranslate-UnableToInstall](https://user-images.githubusercontent.com/42923035/82102857-e0fffb80-96de-11ea-9f31-b94d408cc06b.PNG)

Is there a fix set to be released or any workaround to get this working?

**Comment by andreicristianpetcu** [comment]
https://github.com/andreicristianpetcu/google_translate_this/issues/19

try this https://addons.mozilla.org/en-US/firefox/addon/s3_translator/

I don't work on this anymore

**Comment by 109isaque10** [comment]
GUYS IF FOUND A WAY, just go to about:config and search extensions.blocklist.enabled and double click it to set it to false.

**Comment by HashAbdulla** [comment]
> GUYS IF FOUND A WAY, just go to about:config and search extensions.blocklist.enabled and double click it to set it to false.

WWWWW, still working june 2024
