### ISSUE TITLE
Be able to hit "translate page" once instead of having to press it for every new window

### ISSUE THREAD

**Issue by lich1708** [andreicristianpetcu/google_translate_this#5]
Title says it all. I'm lurking a lot on a russian site and I find it quite annoying to hit the "translate page" every time I browse through the site. Wouldn't it be possible to add certain sites so your addon knows that "this specific site should auto-translate every new window/tab". 

Brilliant app btw. Hope I don't sound like I'm complaining or anything. English isn't my first language.

**Comment by andreicristianpetcu** [comment]
I'll try to work on this soon. I make no promises. The thing is...... I also need this feature :smile:

**Comment by andreicristianpetcu** [comment]
Please force an update and re-test @lich1708 I fixed the issue in version 2.0.2.
Currently all translate options only translate per domain, not per page like it used to. This is per session so after restart it will forget the sites where you had always translate.
