### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by dav9597** [andreicristianpetcu/google_translate_this#8]
Hey mate, was just here asking if you have any news about mobile development. I use this so much on desktop, and I urgently need it on mobile too. Thanks

**Comment by dav9597** [comment]
Sorry also if this is a bad sector to ask this

**Comment by andreicristianpetcu** [comment]
Fair question. I have no deadline for it. I would like to implement support some time but until then you can use this one https://github.com/jeremiahlee/page-translator

**Comment by dav9597** [comment]
I didn't know about that one, thanks a lot for the heads up. Will still continue to use yours on desktop though ❤️

**Comment by andreicristianpetcu** [comment]
Thank you @dav9597 !

**Comment by andreicristianpetcu** [comment]
Damn! It was A LOT easier than I was expecting :D [test it out](https://github.com/andreicristianpetcu/google_translate_this/releases/download/v2.2.2/google_translate_this_page-2.2.2-fx.xpi)

Also on the releases page https://github.com/andreicristianpetcu/google_translate_this/releases/tag/v2.2.2

**Comment by andreiuipath** [comment]
There is one issue I don't feel like fixing: selecting the language the first time is a pain
![Screenshot_20190818-013710_Firefox](https://user-images.githubusercontent.com/50407920/63217988-f1d40e80-c158-11e9-852f-78729547bcc4.png)
Switch to desktop, select language, switch back to mobile
![Screenshot_20190818-013721_Firefox](https://user-images.githubusercontent.com/50407920/63217996-057f7500-c159-11e9-9d10-421e6e2269b6.png)

**Comment by dav9597** [comment]
Ok, it works. I just find it disturbing that it reloads the page, instead of just instant translating it

**Comment by andreicristianpetcu** [comment]
@dav9597  It only does that for pages with content security policy. For pages without csp it should just translate.

This reload was the solution I found for this https://github.com/andreicristianpetcu/google_translate_this/issues/6

**Comment by andreicristianpetcu** [comment]
I fixed the latest issue. Also I learned that it's better to have different extensions for android and desktop. Please uninstall on android and reinstall. Future updates for android will work normally https://github.com/andreicristianpetcu/google_translate_this/releases/download/v2.2.8/google_translate_this_page-2.2.8-an.xpi

**Comment by dav9597** [comment]
Seems like I don't need page translator anymore 😏😉
