### ISSUE TITLE
option to turn off "always translate" for a domain (from latest update)

### ISSUE THREAD

**Issue by mkeroppi** [andreicristianpetcu/google_translate_this#9]
Thanks.

**Comment by HappyTrix** [comment]
yes please

**Comment by GregoryPINAULT** [comment]
Hello,

I encounter the same issue. Once translated one time, all pages of a domain are translated, even when a i don't want it.

The  option to turn off "always translate" don't work. 

The old behaviour (translating only when I ask for it) was far better.

Thanks

**Comment by andreicristianpetcu** [comment]
Damn! I had no clue the old behavior was desirable for some people :D I will implement it the next time I get to work on it.

I would like to keep domain translation as default. How do you prefer the feature?

1) one time translate option in browser action (the icon in top right)
2) one time translate option for page action (the icon in the url bar) not sure if this is possible
3) one time translate keyboard shortcut
4) option page where you choose if you always want to translate domain or always want to translate the page once
5) any other idea?

**Comment by andreicristianpetcu** [comment]
try this extension, maybe it will work until I fix this issue https://github.com/jeremiahlee/page-translator

**Comment by GregoryPINAULT** [comment]
> 
> 
> Damn! I had no clue the old behavior was desirable for some people :D I will implement it the next time I get to work on it.
> 
> I would like to keep domain translation as default. How do you prefer the feature?
> 
>     1. one time translate option in browser action (the icon in top right)
> 
>     2. one time translate option for page action (the icon in the url bar) not sure if this is possible
> 
>     3. one time translate keyboard shortcut
> 
>     4. option page where you choose if you always want to translate domain or always want to translate the page once
> 
>     5. any other idea?

I think the option 4 would be the best.

**Comment by andreicristianpetcu** [comment]
I was also thinking about 4 but wanted to see other opinions.

**Comment by andreicristianpetcu** [comment]
Here is the mockup of what I'm working on.
![image](https://user-images.githubusercontent.com/922368/63636185-bcf21b00-c674-11e9-9cd0-480a8f08978c.png)
![image](https://user-images.githubusercontent.com/922368/63636187-c54a5600-c674-11e9-8d21-0a51d29759f0.png)

**Comment by andreicristianpetcu** [comment]
Here is the new beta with this feature. Please test https://github.com/andreicristianpetcu/google_translate_this/releases/tag/v2.3.1
@mkeroppi @GregoryPINAULT

**Comment by GregoryPINAULT** [comment]
> 
> 
> Here is the new beta with this feature. Please test https://github.com/andreicristianpetcu/google_translate_this/releases/tag/v2.3.1
> @mkeroppi @GregoryPINAULT

The option page works ! On Firefox ESR for Windows at least. Thanks. Having options for default behaviour is pretty useful.

**Comment by jcosentino** [comment]
Thanks for considering this change! I just wanted to chime in that the reason I liked the old way is so that I can translate a page with foreign text that might not necessarily be in another language. For example: a Youtube video with a lot of international people commenting in different language, or the comment section on a Facebook page with different languages.

**Comment by andreicristianpetcu** [comment]
Did you try the beta @jcosentino ? https://github.com/andreicristianpetcu/google_translate_this/releases/tag/v2.3.1

I need to test it a bit more until I ship it as an update.

**Comment by jcosentino** [comment]
> 
> 
> Did you try the beta @jcosentino ? https://github.com/andreicristianpetcu/google_translate_this/releases/tag/v2.3.1
> 
> I need to test it a bit more until I ship it as an update.

I have. So far, it seems to work with the new option of translating only once. However, with that option enabled, it still says "Always translate [website]" even though it does not, as intended.

**Comment by andreicristianpetcu** [comment]
I'll release a fix next week for this. Thank you for testing @jcosentino
